# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] If you have any global tools to install, do so here.
# RUN npm install -g <your-global-package>

# [Optional] Set up any environment variables here.
# ENV NODE_ENV=development

# [Optional] If you want to run a script after container start, add it here.
# CMD [ "npm", "run", "start:dev" ]
