version: 1

# Development environment configuration for GitHub Copilot Coding Agent
# This ensures the agent has the same environment as the repository

environment:
  # Node.js version to match production
  node_version: "20"
  
  # Environment variables required for development and testing
  variables:
    NODE_ENV: "development"
    APP_NAME: "AssessmentBot-Backend"
    APP_VERSION: "1.0.0"
    LOG_LEVEL: "debug"
    PORT: "3000"

# Tools and dependencies
setup:
  # Install Node.js dependencies
  - run: npm install
  
  # Create test environment file with only GEMINI_API_KEY
  - run: |
      if [ ! -f .test.env ]; then
        cp .test.env.example .test.env
        echo "GEMINI_API_KEY=${GEMINI_API_KEY}" > .test.env
      fi
  
  # Setup Husky hooks
  - run: npm run prepare

# Development commands that should be available
commands:
  # Linting and formatting
  lint:
    run: npm run lint
    description: "Run ESLint to check code quality and British English compliance"
  
  lint_fix:
    run: npm run lint:fix
    description: "Run ESLint and automatically fix issues"
  
  lint_british:
    run: npm run lint:british
    description: "Check for American English spellings and enforce British English"
  
  format:
    run: npm run format
    description: "Format code using Prettier"
  
  # Testing
  test:
    run: npm run test
    description: "Run unit and integration tests"
  
  test_watch:
    run: npm run test:watch
    description: "Run tests in watch mode"
  
  test_coverage:
    run: npm run test:cov
    description: "Run tests with coverage report"
  
  test_e2e:
    run: npm run test:e2e
    description: "Run end-to-end tests"
  
  # Building
  build:
    run: npm run build
    description: "Build the application for production"
  
  # Development server
  dev:
    run: npm run start:dev
    description: "Start development server with hot reload"
  
  debug:
    run: npm run debug
    description: "Start server in debug mode"

# Code quality checks that should be enforced
quality_checks:
  # Pre-commit hooks via Husky and lint-staged
  pre_commit:
    - run: npx lint-staged
      description: "Run linting and formatting on staged files"
  
  # British English compliance check
  british_english:
    - run: ./scripts/check-british-english.sh
      description: "Ensure British English spelling is used throughout the codebase"

# File patterns that should be ignored by the agent
ignore_patterns:
  - "node_modules/**"
  - "dist/**"
  - "coverage/**"
  - "*.log"
  - ".env"
  - ".test.env"
  - ".env.local"
