#!/bin/sh


# Remove junit and coverage folders before commit to avoid merge conflicts
# You can't add these to .gitignore because that will create errors when the `ci.yml` github workflow runs as the github runner won't be able to write to folders in .gitignore.
rm -rf junit coverage

# Run lint-staged (existing checks)
npx lint-staged