name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    env:
      NODE_ENV: test
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test -- --verbose --coverage

      - name: Publish Unit Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: './junit/jest-junit.xml'

  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: lint
    env:
      NODE_ENV: test
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      LLM_BACKOFF_BASE_MS: '2000'
      LLM_MAX_RETRIES: '5'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Create .test.env for E2E tests
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .test.env

      - name: Run E2E tests
        run: npm run test:e2e -- --verbose

      - name: Publish E2E Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: './junit/jest-junit.xml'
