name: Setup Development Environment for Copilot

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  setup-copilot-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create test environment file
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .test.env

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

  validate-pr-quality:
    runs-on: ubuntu-latest
    needs: setup-copilot-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run format -- --check

      - name: Validate British English compliance
        run: |
          echo "Checking for American English spellings that should be British English..."
          if grep -rE '\b(color|flavor|center|defense|authorize|organize)\b' src/ --include="*.ts" --include="*.js" --exclude-dir=node_modules; then
            echo "❌ Found American English spellings. Please use British English (colour, flavour, centre, defence, authorise, organise)"
            exit 1
          else
            echo "✅ British English compliance verified"
          fi

  # This job runs the same checks that Husky would run on commit
  husky-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create test environment file
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .test.env

      - name: Run lint-staged simulation
        run: |
          # Simulate what lint-staged would do on commit
          npx lint-staged --diff="origin/main...HEAD"